on:
  workflow_call:

jobs:
  build-dom:
    name: Build Reveal.Sdk.Dom

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: NuGet Restore
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Run Tests
      run: dotnet test --no-restore --verbosity minimal
