name: Create Draft Release

on:
  workflow_dispatch:

jobs:
  build-and-test:
    name: Build & Test
    uses: ./.github/workflows/build-and-test.yml

  create-draft-release:
    name: Create Draft Release
    runs-on: windows-latest
    needs: build-and-test

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Download NuGet package
      uses: actions/download-artifact@v4
      with:
        name: nuget-package
        path: ./artifacts

    - name: Extract NuGet version from .nupkg filename
      id: nuget_version
      shell: bash
      run: |
        file=$(ls ./artifacts/Reveal.Sdk.Dom.*.nupkg)
        echo "NuGet Package: $file"
        version=$(basename "$file" | sed -E 's/Reveal\.Sdk\.Dom\.([0-9A-Za-z\.-]+)\.nupkg/\1/')
        echo "Version: $version"
        echo "version=$version" >> "$GITHUB_OUTPUT"

    - name: Create GitHub draft release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.nuget_version.outputs.version }}
        name: ${{ steps.nuget_version.outputs.version }}
        draft: true
        generate_release_notes: true
        files: |
          ./artifacts/*.nupkg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
