name: PR Validation

on:
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    name: Build & Test Reveal.Sdk.Dom

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src

    strategy:
      matrix:
        dotnet-version: [6.0.x, 7.0.x, 8.0.x, 9.0.x]

    steps:
      - uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Generate global.json for SDK pinning
        run: |
          VERSION=$(dotnet --version)
          echo "{ \"sdk\": { \"version\": \"$VERSION\" } }" > ../../global.json

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Run tests
        run: dotnet test --no-build --verbosity normal
