name: Publish to NuGet

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Download release asset (.nupkg)
      id: download
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mkdir -p nupkg
        release_url="https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ github.event.release.tag_name }}"
        asset_url=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" $release_url | jq -r '.assets[] | select(.name | endswith(".nupkg")) | .url')
        filename=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" $release_url | jq -r '.assets[] | select(.name | endswith(".nupkg")) | .name')
        echo "Downloading $filename from $asset_url"
        curl -L -H "Authorization: Bearer $GITHUB_TOKEN" -H "Accept: application/octet-stream" "$asset_url" -o "./nupkg/$filename"
        echo "filename=$filename" >> "$GITHUB_OUTPUT"

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.x

    - name: Push to NuGet.org
      run: dotnet nuget push "./nupkg/${{ steps.download.outputs.filename }}" --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
